webapp1:
  image: web
  expose:
      - "8080"
  links:
    - "mysql"
webapp2:
  image: web
  expose:
      - "8080"
  links:
    - "mysql"
webapp3:
  image: web
  expose:
      - "8080"
  links:
    - "mysql"
webapp4:
  image: web
  expose:
      - "8080"
  links:
    - "mysql"
nginx:
  image: nginx
  ports:
    - 19000:9000
    - 18888:8888
  volumes:
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/www:/var/www
  links:
    - webapp1
    - webapp2
    - webapp3
    - webapp4
mysql:
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=bignibou
  volumes:
   - ./mysql/db:/var/lib/mysql
  ports:
    - "5566:3306"
