webapp1:
  image: web
  ports:
    - "3031:8080"
webapp2:
  image: web
  ports:
    - "3032:8080"
webapp3:
  image: web
  ports:
    - "3033:8080"
webapp4:
  image: web
  ports:
    - "3034:8080"
nginx:
  image: nginx
  ports:
    - 5000:8888
  volumes:
    - ./nginx/conf:/etc/nginx/conf.d
    - ./nginx/www:/var/www
