webapp1:
  image: web
  ports:
    - "3031:8080"
  links:
    - "mysql"
webapp2:
  image: web
  ports:
    - "3032:8080"
  links:
    - "mysql"
webapp3:
  image: web
  ports:
    - "3033:8080"
  links:
    - "mysql"
webapp4:
  image: web
  ports:
    - "3034:8080"
  links:
    - "mysql"
nginx:
  image: nginx
  ports:
    - 5000:8888
  volumes:
    - ./nginx/conf:/etc/nginx/conf.d
    - ./nginx/www:/var/www
mysql:
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=bignibou
  volumes:
   - ./mysql/db:/var/lib/mysql
  ports:
    - "5566:3306"
